version: 0.2
phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run env
      - npm run test-unit
      - npm run infra:deploy --stage test
      - npm run test-integration
  build:
    commands:
      - npm run api:deploy --stage test
      - npm run test-e2e
