version: 0.2
phases:
  install:
    commands:
      - npm ci
  pre_build:
    commands:
      - npm run test-unit
  build:
    commands:
      - npm run infra:deploy
      - npm run api:deploy
      - npm run env
      - npm run test-integration
      - npm run test-e2e
