Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:custom.appName}-users-${self:provider.stage}
      Policies:
        PasswordPolicy:
          MinimumLength: 12
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      UserPoolTags:
        PROJECT: ${file(../../common/infra/provider-settings.yml):appName}
        SERVICE: ${self:service}

  CognitoUserPoolStaffClient:
    Type: 'AWS::Cognito::UserPoolClient'
    #DeletionPolicy: Retain
    Properties:
      ClientName: ${self:custom.appName}-staff-client-${self:provider.stage}
      GenerateSecret: false
      UserPoolId: !Ref CognitoUserPool
      ExplicitAuthFlows:
        - USER_PASSWORD_AUTH

Outputs:
  UserPoolId:
    Description: ID of the User Pool
    Value: !Ref CognitoUserPool
  UserPoolArn:
    Description: ARN of the User Pool
    Value: !GetAtt CognitoUserPool.Arn
  UserPoolStaffClientId:
    Description: ID of the User Pool Client
    Value: !Ref CognitoUserPoolStaffClient
