Resources:
  # TODO: Enable "DeletionPolicy" and "UpdateReplacePolicy" on DynamoDB tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    #    DeletionPolicy: ${self:custom.deletionPolicy.${self:provider.stage}}
    #    UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  RestaurantsTable:
    Type: AWS::DynamoDB::Table
    #    DeletionPolicy: ${self:custom.deletionPolicy.${self:provider.stage}}
    #    UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}-restaurants
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: region
          AttributeType: S
        - AttributeName: visibility
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: RestaurantsByVisibilityAndRegion
          KeySchema:
            - AttributeName: visibility
              KeyType: HASH
            - AttributeName: region
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  SeatingsTable:
    Type: AWS::DynamoDB::Table
    #    DeletionPolicy: ${self:custom.deletionPolicy.${self:provider.stage}}
    #    UpdateReplacePolicy: Retain
    Properties:
      TableName: ${self:custom.dynamoDbTablePrefix}-seatings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: restaurantId
          AttributeType: S
        - AttributeName: seatingTime
          AttributeType: S
      KeySchema:
        - AttributeName: restaurantId
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
        - IndexName: SeatingsByRestaurantAndSeatingTime
          KeySchema:
            - AttributeName: restaurantId
              KeyType: HASH
            - AttributeName: seatingTime
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Dead letter queue for failed DDB stream events
  DDBSeatingsStreamDLQ:
    Type: AWS::SQS::Queue

Outputs:
  DDBTableUsers:
    Value: !Ref UsersTable
  DDBTableRestaurants:
    Value: !Ref RestaurantsTable
  DDBTableSeatings:
    Value: !Ref SeatingsTable
  DDBTableSeatingsStreamArn:
    Value: !GetAtt SeatingsTable.StreamArn
  DDBSeatingsStreamDLQ:
    Value: !Ref DDBSeatingsStreamDLQ
  DDBSeatingsStreamDLQArn:
    Value: !GetAtt DDBSeatingsStreamDLQ.Arn
